### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by thomas-coichot** [PrestaShop/ps_featuredproducts#21] opened 2019-08-05 13:09 UTC
![Capture d’écran 2019-08-05 à 14 33 28](https://user-images.githubusercontent.com/35110724/62466989-fed52300-b792-11e9-901b-ad1858e60b59.png)
![Capture d’écran 2019-08-05 à 14 33 45](https://user-images.githubusercontent.com/35110724/62466992-00065000-b793-11e9-9e85-a685b3940b26.png)

Prestahop : 1.7.6
PHP: 7.2.16

**Comment by khouloudbelguith** [comment] 2019-08-05 13:16
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/14990

**Closed as completed by khouloudbelguith** 2019-08-05 13:16 UTC
Labels: duplicate
